### PR TITLE
Update qutip to 5.0.1

### PR DESCRIPTION
**Pull request by hodgestar**
This updates the qutip recipe to build qutip 5.0.1.

In addition to updating the version number and the package hash, it also updates the tests.

### CODE REVIEW

**Comment by hodgestar** [comment]
Failed with:
```
FAILED test_qutip.py::test_qobj_create - ModuleNotFoundError: No module named 'setuptools'
```

**Comment by martinRenou** [comment]
This is really odd. Qutip does not import anything from setuptools in the source https://github.com/qutip/qutip/blob/master/qutip/core/__init__.py

**Comment by hodgestar** [comment]
@martinRenou Thank you for taking a look. `setuptools` is imported via `qutip/core/coefficient.py` which is imported in `qutip/core/__init__.pu`. Setuptools was intended to be an optional dependency though, so 5.0.1 has been released to fix that.

**Comment by hodgestar** [comment]
Yay, tests are passing. Ready for review.

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
Closes #849

**Comment by hodgestar** [comment]
Thank you!

**Pull request merged**
