### PR TITLE
per recipe pr

### PR DESCRIPTION
**Pull request by DerThorsten**
this creates a single PR for each recipe where a new version is available

### CODE REVIEW

**Comment by wolfv** [comment]
You'll have the issue of having to build them in order though (with static linking etc.), right?

**Comment by DerThorsten** [comment]
> You'll have the issue of having to build them in order though (with static linking etc.), right?

 I cannot follow


This is basically just to have a lot of tiny PRs instead of one PR with a lot of changes...

**Comment by DerThorsten** [comment]
jeah it should replace the old, but I wanted to see if its indeed working.
So we can merge this as is, and try it out.
If its works well from the CI we can replace the other script

**Comment by DerThorsten** [comment]
there is a tiny issue still...the PR title have the old instead of the new version =)

**Comment by martinRenou** [comment]
Are we not missing an author for the commit? For when it's ran on the action?

**Comment by DerThorsten** [comment]
> Are we not missing an author for the commit? For when it's ran on the action?

not sure, got the main idea from StackOverflow:
https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action

**Comment by DerThorsten** [comment]
> If bzip2 is updated in one PR, and Python is updated in another PR and they are merged Python first, then bzip2, then the Python build would still be linking to the older bzip2, right?
> 
> Might not be much of an issue, but just something to keep in mind.

I am willing to live with that risk!

**Pull request merged**
