### PR TITLE
Update pandas to 2.0.0

### PR DESCRIPTION
**Pull request by jtpio**
Try updating to the latest pandas which was just released on PyPI: https://pypi.org/project/pandas/2.0.0/

- [x] Bump `pandas` to `2.0.0`
- [x] Remove the patch as it does not seem to be needed anymore: https://github.com/pyodide/pyodide/pull/3134

### CODE REVIEW

**Comment by DerThorsten** [comment]
versioneer seems to be missing

**Comment by jtpio** [comment]
@DerThorsten is this PR closed because pandas was updated in another PR?

**Comment by DerThorsten** [comment]
I closed all bot created PRs (by looking which PR started with "Updating ****") because otherwise the bot will not create fresh PRs with a rattler compatible recipe.

This PR looks like a bot PR on the first glance.

**Comment by DerThorsten** [comment]
this PR needs to be updated to the rattler recipe format https://github.com/prefix-dev/rattler-build?tab=readme-ov-file#the-recipe-format

**Comment by jtpio** [comment]
Ah ok thanks for the context.

Then maybe it would be better to start over.

**Comment by DerThorsten** [comment]
pandas 2.0 landed via #526

**Pull request closed without merging**
