### PR TITLE
Update wasm-request package

### PR DESCRIPTION
**Pull request by martinRenou**
- [x] TODO Add a `requests` output that pins to the polyfill

### CODE REVIEW

**Comment by martinRenou** [comment]
@wolfv There might be versioning mismatch with this approach. If another conda package relies on `requests>=1,<2` they simply won't get it.

Do you know if we can work around this?

**Comment by martinRenou** [comment]
Ideally we'd match the requests API exactly and respect the same versioning.

**Comment by wolfv** [comment]
looks good to me. I don't know what to do about versioning. I guess any requests usage out of the ordinary would break pretty soon, anyways, right?

**Comment by martinRenou** [comment]
Yes. For now it only provides the basic features.

**Comment by martinRenou** [comment]
Thanks for the review!

**Pull request merged**
