### PR TITLE
Update xeus-python to 0.16

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
@DerThorsten are we safe with this one? Has all the pyjs -> pyjs_core imports been updated correctly?

**Comment by DerThorsten** [comment]
> @DerThorsten are we safe with this one? Has all the pyjs -> pyjs_core imports been updated correctly?

the pyjs unit test pass by importing pyjs, pyjs itself then imports pyjs_core.
So I believe we should be save...(famous last words)

**Comment by DerThorsten** [comment]
Actually, I am very confident as I already have a deployment with the changes at https://emscripten-forge.github.io/pyjs/try_from_py/

**Comment by martinRenou** [comment]
Oups. I forgot to reset the build number. I guess this is not so harmful though?

**Comment by DerThorsten** [comment]
no not a problem

**Pull request merged**
