### PR TITLE
Add xeus-cpp

### PR DESCRIPTION
**Pull request by alexander-penev**

### CODE REVIEW

**Comment by mcbarton** [comment]
As you've got it to download the tar for the main the sha is now out of date, as a new commit(s) have been made.

**Comment by mcbarton** [comment]
> As you've got it to download the tar for the main the sha is now out of date, as a new commit(s) have been made.

Maybe worth reverting back to downloading the tar for version 0.4.0

**Comment by alexander-penev** [comment]
Yes, download from main was temporary try to workaround patch problem. Now patch is not needed and we use release 0.4.0.

**Comment by vgvassilev** [comment]
@DerThorsten, thanks for merging this. It seems that the build after merging this PR has a problem: https://github.com/emscripten-forge/recipes/actions/runs/9049611938/job/24863926846 Do you have an idea what's going wrong here?

**Comment by DerThorsten** [comment]
> @DerThorsten, thanks for merging this. It seems that the build after merging this PR has a problem: https://github.com/emscripten-forge/recipes/actions/runs/9049611938/job/24863926846 Do you have an idea what's going wrong here?

there was a missing dependency in the environment of the ci, I rebuild xeus-cpp in #938 to trigger a reupload

**Comment by DerThorsten** [comment]
https://beta.mamba.pm/channels/emscripten-forge/packages/xeus-cpp

**Pull request merged**
