### PR TITLE
Update version 1.24

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by martinRenou** [comment]
I suppose the sha will need an update

**Comment by davidbrochart** [comment]
Damn cat :smile:

**Comment by davidbrochart** [comment]
The [failure](https://github.com/emscripten-forge/recipes/actions/runs/4186187767/jobs/7254334118) doesn't say a lot.

**Comment by martinRenou** [comment]
I understand that one patch does not apply anymore, there may be conflicts, we may need to update it

**Comment by wolfv** [comment]
yep, exactly

**Comment by martinRenou** [comment]
Seems to build properly and tests are passing now. We just hit the same pyjs/pyjs_code_runner incompatibility we've seen in other PRs.

**Comment by DerThorsten** [comment]
we need to re-trigger this job! then it can work again

**Comment by DerThorsten** [comment]
https://github.com/emscripten-forge/pyjs-code-runner/pull/4 was needed

**Review by DerThorsten — APPROVED** [review]

**Pull request merged**
