### PR TITLE
refactor some recipes

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by DerThorsten** [comment]
I wonder why this does not trigger the CI

**Comment by wolfv** [comment]
let me rebase.

**Comment by DerThorsten** [comment]
strange..it does  not use the complete build matrix (the part where we *not* skip existing is not running)

**Comment by DerThorsten** [comment]
oh wait..actually not that strange @wolfv lets add the other stuff to the matrix again...

**Comment by DerThorsten** [comment]
nice its green

**Comment by wolfv** [comment]
I'll let you squash and merge :)

**Pull request merged**
