### PR TITLE
Update pydro v0.1.2

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure why it fails, there's almost no difference with v0.1.1.

**Comment by martinRenou** [comment]
The error seems unrelated:

```
TypeError: importPackages is not a function\n    at make_pyjs
```

My guess is an incompatibility between pyjs and the pyjs test runner.

**Comment by DerThorsten** [comment]
this is related to some empack change. I investigate now

**Comment by DerThorsten** [comment]
https://github.com/emscripten-forge/pyjs-code-runner/pull/4 this should fix it!

**Review by DerThorsten — APPROVED** [review]

**Pull request merged**
