### PR TITLE
Add r-lifecycle

### PR DESCRIPTION
**Pull request by anutosh491**

### CODE REVIEW

**Comment by anutosh491** [comment]
Should be rebased after #1364 goes in

**Review by IsabelParedes — CHANGES_REQUESTED** [review]
This is a pure R package and **noarch**, we shouldn't need to build it.

**Comment by anutosh491** [comment]
> This is a pure R package and noarch, we shouldn't need to build it.

Yes. We shouldn't need to but I found the issue we found on `r-vctrs` on any package that is r-lifecycle dependent. But I could get all those building straightaway once I built r-lifecycle. Maybe add it for now and we can remove it later ? (I guess once a newer version is released ... technically r-lifecycle should support R 4.4.1 :| ) 
I could open an issue for the same to track this if the above makes sense ?

**Comment by IsabelParedes** [comment]
Let's try rebasing r-vctrs with the new r-cli and come back to this one later if we need it.

**Comment by anutosh491** [comment]
Closing as not rquired.

**Pull request closed without merging**
