### PR TITLE
Add idyntree recipe

### PR DESCRIPTION
**Pull request by traversaro**
Based on https://github.com/conda-forge/idyntree-feedstock but with several dependencies disabled as they are not available in emscripten-forge .

### CODE REVIEW

**Comment by traversaro** [comment]
Build failed with:
~~~
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - libxml
 - eigen
 - pip 22.0.4*
 - python 3.10.* *_cpython
 - numpy 1.21.4*
 - python_abi 3.10.* *_cp310
with channels:
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested eigen
~~~

Probably due to https://github.com/emscripten-forge/recipes/pull/121#issuecomment-1189454177 .

**Comment by traversaro** [comment]
Now the recipe is creating problems with:
~~~
2022-07-19T21:52:34.9678214Z EMSDK = /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/lib/python3.10/site-packages/emsdk
2022-07-19T21:52:34.9678935Z EM_CONFIG = /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/lib/python3.10/site-packages/emsdk/.emscripten
2022-07-19T21:52:34.9679697Z EMSDK_NODE = /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/lib/python3.10/site-packages/emsdk/node/14.18.2_64bit/bin/node
2022-07-19T21:52:34.9680218Z Clearing existing environment variable: EMSDK_PYTHON
2022-07-19T21:52:35.9399833Z configure: cmake -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -GNinja .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL= -DIDYNTREE_USES_IPOPT:BOOL=OFF -DIDYNTREE_USES_OSQPEIGEN:BOOL=OFF -DIDYNTREE_USES_IRRLICHT:BOOL=OFF -DIDYNTREE_USES_ASSIMP:BOOL=OFF -DIDYNTREE_USES_MATLAB:BOOL=OFF -DIDYNTREE_USES_PYTHON:BOOL=ON -DIDYNTREE_USES_OCTAVE:BOOL=OFF -DIDYNTREE_USES_LUA:BOOL=OFF -DIDYNTREE_COMPILES_YARP_TOOLS:BOOL=OFF -DPython3_EXECUTABLE:PATH=/home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/bin/python -DIDYNTREE_DETECT_ACTIVE_PYTHON_SITEPACKAGES:BOOL=ON -DIDYNTREE_PYTHON_PIP_METADATA_INSTALLER=conda -DCMAKE_TOOLCHAIN_FILE=/home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/lib/python3.10/site-packages/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/lib/python3.10/site-packages/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads
2022-07-19T21:52:37.0772695Z [31mCMake Error at /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
2022-07-19T21:52:37.0773276Z   Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
2022-07-19T21:52:37.0773945Z Call Stack (most recent call first):
2022-07-19T21:52:37.0774795Z   /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
2022-07-19T21:52:37.0775575Z   /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658267451408/_build_env/share/cmake-3.23/Modules/FindLibXml2.cmake:108 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
2022-07-19T21:52:37.0776047Z   cmake/iDynTreeDependencies.cmake:66 (find_package)
2022-07-19T21:52:37.0776336Z   CMakeLists.txt:39 (include)
~~~

At a first glance, it is some kind of strange interation between `find_package`/`find_library`/`find_file` and the emscripten toolchain, I experienced something similar with https://github.com/microsoft/vcpkg/pull/11753 . Related to that, who is setting the `CMAKE_ARGS` env variable? I checked it and it contains:
~~~
-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON
~~~
but according to CMake docs, the only valid values are `ÒNLY`, `NEVER` or `BOTH` see https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH_MODE_PACKAGE.html . It is not clear from docs what happens if you set it to `ON`.

**Comment by wolfv** [comment]
Looks like that particular variable is on our end: https://github.com/emscripten-forge/recipes/blob/ba3e52331aa7e21f34e3c2d0ba17db57b56233ea/recipes/recipes/emscripten_emscripten-32/activate.sh#L15 :bow:

Do you want to send a PR?

I'll check the libxml package

**Comment by wolfv** [comment]
In the libxml package (https://beta.mamba.pm/get/emscripten-forge/emscripten-32/libxml-2.9.10-h1a65802_0.tar.bz2) I found a cmake file under:

`lib/cmake/libxml2/libxml2-config.cmake` 

However, the cmake file itself seems also slightly broken, as it reads:

```
list(APPEND LIBXML2_LIBRARIES  -L/home/runner/micromamba/envs/ci-env/conda-bld/libxml_1652202972834/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/lib -lm  )
```

(instead of `lib/libxml2` or `lib libxml2` it says `lib/lib`, seems weird!)

**Comment by traversaro** [comment]
In this specific case I do not think that ``lib/cmake/libxml2/libxml2-config.cmake` is the culprit, as idyntree looks for via LibXml2 via `find_package(LibXml2 REQUIRED)` (see https://github.com/robotology/idyntree/blob/fb0b5d311775149afce1e97562c0b418d04a70d5/cmake/iDynTreeDependencies.cmake#L66), so the file that is used is [`FindXml2.cmake`  that ships with CMake](https://github.com/Kitware/CMake/blob/v3.23.2/Modules/FindLibXml2.cmake), and that files does not use `find_package(LibXml2 CONFIG)` internally.

**Comment by wolfv** [comment]
I updated our version of libxml2 in #126 (also changed the name of the package from `libxml` to `libxml2`.
We could give that a shot when the recipe passes. What do you think?

**Comment by traversaro** [comment]
> Looks like that particular variable is on our end:
> 
> https://github.com/emscripten-forge/recipes/blob/ba3e52331aa7e21f34e3c2d0ba17db57b56233ea/recipes/recipes/emscripten_emscripten-32/activate.sh#L15
> 🙇
> 
> Do you want to send a PR?
> 

Ack, however I need to look a bit more in depth, because that variable should be already set by the Emscripten CMake platform (see https://github.com/emscripten-core/emscripten/blob/df8782c195da6761f9fce976fc4fc79687b45f0f/cmake/Modules/Platform/Emscripten.cmake#L262). What instead seems to be missing (and that if fixed could make `find_package(LibXml2 REQUIRED)` work) is setting `CMAKE_FIND_ROOT_PATH`, that is the variable that is used if `CMAKE_FIND_ROOT_PATH_MODE_*` variables are enabled.

**Comment by traversaro** [comment]
Ok, switching to `find_package(LibXml2 REQUIRED CONFIG)` LibXml2 is found correctly. Now Python is not found, for some reason.

**Comment by wolfv** [comment]
@traversaro we made pretty good progress on some other python libraries (scipy, scikit-image, scikit-learn) recently :)

I would love to help to get this one over the finish line, too!

It looks like it finds the `swig` installation from the host system. Is that OK / desired? We do not have a cross-compiled swig yet, afaik.

**Comment by traversaro** [comment]
> It looks like it finds the `swig` installation from the host system. Is that OK / desired? We do not have a cross-compiled swig yet, afaik.

Yes, swig` is a tool for code generation that tipically runs on the host system, so I would say this is intended and ok.

The problem here seems:
~~~
CMake Error at /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658302861540/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS
  Python3_NumPy_INCLUDE_DIRS Development.Module NumPy) (found version
  "3.10.5")
Call Stack (most recent call first):
  /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658302861540/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658302861540/_build_env/share/cmake-3.23/Modules/FindPython/Support.cmake:3192 (find_package_handle_standard_args)
  /home/runner/micromamba-root/envs/ci-env/conda-bld/idyntree_1658302861540/_build_env/share/cmake-3.23/Modules/FindPython3.cmake:490 (include)
  bindings/CMakeLists.txt:44 (find_package)
~~~

I wanted to debug this locally, but I tried to setup a local system to test but I was not able to do it.

**Comment by wolfv** [comment]
Sorry about that, we should get our local dev docs in order. For the moment, if you follow the steps of the github action it should be reasonably straight forward.
The main thing is to install the `ci_env.yml` from this environment, and two custom packages via `pip`.

**Comment by DerThorsten** [comment]
> @traversaro we made pretty good progress on some other python libraries (scipy, scikit-image, scikit-learn) recently :)
> 
> I would love to help to get this one over the finish line, too!
> 
> It looks like it finds the `swig` installation from the host system. Is that OK / desired? We do not have a cross-compiled swig yet, afaik.

actually we have `swiglpk` uses swig https://github.com/emscripten-forge/recipes/blob/a41d943c11aed11cffd3f75345392fa2007d7e6e/recipes/recipes_emscripten/swiglpk/recipe.yaml#L19

**Comment by traversaro** [comment]
> Sorry about that, we should get our local dev docs in order. For the moment, if you follow the steps of the github action it should be reasonably straight forward. The main thing is to install the `ci_env.yml` from this environment, and two custom packages via `pip`.
> 
> And install & activate `emsdk`.

Yes, that is what I tried, but I got lost in the process. 

Anyhow, it should be possible to specify the swig to use via the `SWIG_EXECUTABLE` CMake variable, see https://cmake.org/cmake/help/latest/module/FindSWIG.html .

**Comment by traversaro** [comment]
Thanks for all the help @wolfv ! For the time being I do not plan to work on this in the next days, so I can close it and I will reopen it later.

**Comment by wolfv** [comment]
Is CMake not finding numpy? :/

Maybe the `$Python3_EXECUTABLE` should point to `$BUILD_PREFIX/bin/python` so that it can be run?

**Comment by traversaro** [comment]
> Is CMake not finding numpy? :/

Indeed. I was trying to just specify it manually, but it seems that the directory `lib/python3.10/site-packages/numpy` at some point is empty. Even running `mamba list -p $PREFIX`  returns:
~~~
2022-10-10T07:42:39.9661073Z # Name                    Version                   Build  Channel
2022-10-10T07:42:39.9661737Z eigen                     3.4.0                h39b0648_0    https://repo.mamba.pm/emscripten-forge/emscripten-32
2022-10-10T07:42:39.9662442Z libiconv                  1.16                 h1a65802_0    https://repo.mamba.pm/emscripten-forge/emscripten-32
2022-10-10T07:42:39.9663137Z libxml                    2.9.10               h1a65802_0    https://repo.mamba.pm/emscripten-forge/emscripten-32
2022-10-10T07:42:39.9663851Z python                    3.10.2          h_hash_6_cpython    https://repo.mamba.pm/emscripten-forge/emscripten-32
2022-10-10T07:42:39.9664673Z python_abi                3.10                    0_cp310    https://repo.mamba.pm/emscripten-forge/emscripten-32
2022-10-10T07:42:39.9666024Z zlib                      1.2.12               h672cd09_0    https://repo.mamba.pm/emscripten-forge/emscripten-32
~~~

and `ls -R $PREFIX` : 

~~~
2022-10-10T07:42:31.6173625Z $PREFIX/lib/python3.10/site-packages:
2022-10-10T07:42:31.6173730Z 
2022-10-10T07:42:31.6173970Z $PREFIX/lib/python3.10/sqlite3:
~~~

Could this be related to this error:
~~~
2022-10-10T07:41:41.3075230Z Linking numpy-1.21.4-py310h672cd09_0
2022-10-10T07:41:41.3989635Z warning  libmamba [numpy-1.21.4-py310h672cd09_0] The following files were already present in the environment:
2022-10-10T07:41:41.3990180Z     - bin/python
2022-10-10T07:41:41.3990912Z     - bin/python.bak
2022-10-10T07:41:41.5029609Z Transaction finished
~~~

Indeed, it is quite strange that numpy packages contains `bin/python` .

**Comment by traversaro** [comment]
> Maybe the `$Python3_EXECUTABLE` should point to `$BUILD_PREFIX/bin/python` so that it can be run?

I don't think so, for all the cross-compilation builds on conda-forge  in which the python libs are linked I always set `$Python3_EXECUTABLE` to `$PREFIX/bin/python` to ensure that also for the library to link CMake find the host one.

**Comment by traversaro** [comment]
After some fixes, I am able to compile, but the linking fails with:
~~~
2022-10-10T15:42:42.6517625Z [150/153] Linking CXX executable bin/idyntree-model-info.js
2022-10-10T15:42:42.6518056Z [31mFAILED: [0mbin/idyntree-model-info.js 
2022-10-10T15:42:42.6519321Z : && $BUILD_PREFIX/lib/python3.10/site-packages/emsdk/upstream/emscripten/em++ -fdiagnostics-color=always -O3 -DNDEBUG -s SIDE_MODULE=1 src/tools/CMakeFiles/idyntree-model-info.dir/idyntree-model-info.cpp.o -o bin/idyntree-model-info.js  lib/libidyntree-core.a  lib/libidyntree-model.a  lib/libidyntree-high-level.a  lib/libidyntree-modelio.a  lib/libidyntree-visualization.a  lib/libidyntree-solid-shapes.a  lib/libidyntree-modelio-xml.a  $PREFIX/lib/libxml2.a  lib/libidyntree-sensors.a  lib/libidyntree-model.a  lib/libidyntree-core.a && :
2022-10-10T15:42:42.6520394Z em++: warning: output suffix .js requested, but wasm side modules are just wasm files; emitting only a .wasm, no .js [-Wemcc]
2022-10-10T15:42:42.6520915Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactPoint()
2022-10-10T15:42:42.6521297Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6521646Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6521815Z 
2022-10-10T15:42:42.6522085Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactPoint() const
2022-10-10T15:42:42.6522464Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6522820Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6522984Z 
2022-10-10T15:42:42.6523240Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactWrench()
2022-10-10T15:42:42.6523612Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6523953Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6524115Z 
2022-10-10T15:42:42.6524384Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactWrench() const
2022-10-10T15:42:42.6524764Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6525113Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6525278Z 
2022-10-10T15:42:42.6525525Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactId()
2022-10-10T15:42:42.6525890Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6526225Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6526383Z 
2022-10-10T15:42:42.6526639Z wasm-ld: error: duplicate symbol: iDynTree::ContactWrench::contactId() const
2022-10-10T15:42:42.6527116Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6527467Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6527627Z 
2022-10-10T15:42:42.6527931Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::LinkContactWrenches(unsigned long)
2022-10-10T15:42:42.6528333Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6528690Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6528837Z 
2022-10-10T15:42:42.6529117Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::resize(unsigned long)
2022-10-10T15:42:42.6529504Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6529855Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6530016Z 
2022-10-10T15:42:42.6530333Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::LinkContactWrenches(iDynTree::Model const&)
2022-10-10T15:42:42.6530749Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6531101Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6531261Z 
2022-10-10T15:42:42.6531535Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::resize(iDynTree::Model const&)
2022-10-10T15:42:42.6532836Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6533388Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6533609Z 
2022-10-10T15:42:42.6534220Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::contactWrench(long, unsigned long) const
2022-10-10T15:42:42.6534805Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6535286Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6535506Z 
2022-10-10T15:42:42.6536189Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::contactWrench(long, unsigned long)
2022-10-10T15:42:42.6536574Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6536925Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:42.6537087Z 
2022-10-10T15:42:42.6537690Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::getNrOfLinks() const
2022-10-10T15:42:46.6075052Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6076206Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6076400Z 
2022-10-10T15:42:46.6076838Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::getNrOfContactsForLink(long) const
2022-10-10T15:42:46.6077584Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6078435Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6078657Z 
2022-10-10T15:42:46.6079111Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::setNrOfContactsForLink(long, unsigned long)
2022-10-10T15:42:46.6079663Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6080152Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6080371Z 
2022-10-10T15:42:46.6080827Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::computeNetWrenches(iDynTree::LinkWrenches&) const
2022-10-10T15:42:46.6082344Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6082878Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6083066Z 
2022-10-10T15:42:46.6083450Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::toString(iDynTree::Model const&) const
2022-10-10T15:42:46.6083890Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6084281Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6084464Z 
2022-10-10T15:42:46.6084805Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::LinkContactWrenches(unsigned long)
2022-10-10T15:42:46.6085250Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6085941Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6086120Z 
2022-10-10T15:42:46.6086478Z wasm-ld: error: duplicate symbol: iDynTree::LinkContactWrenches::LinkContactWrenches(iDynTree::Model const&)
2022-10-10T15:42:46.6086932Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6087305Z >>> defined in lib/libidyntree-model.a(ContactWrench.cpp.o)
2022-10-10T15:42:46.6087488Z 
2022-10-10T15:42:46.6087940Z wasm-ld: error: duplicate symbol: iDynTree::DHChain::setNrOfDOFs(unsigned long)
2022-10-10T15:42:46.6088369Z >>> defined in lib/libidyntree-model.a(DenavitHartenberg.cpp.o)
2022-10-10T15:42:46.6088764Z >>> defined in lib/libidyntree-model.a(DenavitHartenberg.cpp.o)
2022-10-10T15:42:46.6088950Z 
2022-10-10T15:42:46.6089224Z wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
2022-10-10T15:42:46.6092216Z em++: error: '$BUILD_PREFIX/lib/python3.10/site-packages/emsdk/upstream/bin/wasm-ld -o bin/idyntree-model-info.js --whole-archive src/tools/CMakeFiles/idyntree-model-info.dir/idyntree-model-info.cpp.o lib/libidyntree-core.a lib/libidyntree-model.a lib/libidyntree-high-level.a lib/libidyntree-modelio.a lib/libidyntree-visualization.a lib/libidyntree-solid-shapes.a lib/libidyntree-modelio-xml.a $PREFIX/lib/libxml2.a lib/libidyntree-sensors.a lib/libidyntree-model.a lib/libidyntree-core.a -L$BUILD_PREFIX/lib/python3.10/site-packages/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic --no-whole-archive -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --strip-debug --export-dynamic --no-gc-sections --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=setThrew --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=malloc --export-if-defined=free --export-if-defined=ntohs --export-if-defined=htons --export-if-defined=__dl_seterr --export-if-defined=htonl --experimental-pic -shared' failed (returned 1)
2022-10-10T15:42:46.6094395Z [151/153] Swig compile ../iDynTree.i for python
~~~

Probably this is an upstream problem, so I can close this PR and investigate this upstream eventually.

**Pull request closed without merging**
