### PR TITLE
add cf_units

### PR DESCRIPTION
**Pull request by ocefpaf**
@wolfv this adds `cf_units` and should work as a "poor's man" test for udunits2 too.

### CODE REVIEW

**Comment by wolfv** [comment]
Cool!

**Comment by ocefpaf** [comment]
@wolfv this is probably what I was afraid of, udunits2 is not functional without an activation script like https://github.com/conda-forge/udunits2-feedstock/blob/main/recipe/scripts/activate.sh. We can probably hardcode stuff. I'll investigate what the pyodide folks do in cases like these.

**Comment by wolfv** [comment]
I think I also looked at this back then, and I thought it would be possible to patch the correct value into the binary.

**Comment by ocefpaf** [comment]
> I think I also looked at this back then, and I thought it would be possible to patch the correct value into the binary.

Cool. I'd like to avoid what was done in pyodide b/c it leads an increase in size when we need to copy data files over to each wheel that requires them. I'm sure they are looking into better options too.

**Comment by DerThorsten** [comment]
this needs to be converted to the new [rattler-recipe format](https://github.com/prefix-dev/rattler-build?tab=readme-ov-file#the-recipe-format)

**Comment by DerThorsten** [comment]
closing because of inactivity

**Pull request closed without merging**
