### PR TITLE
Add ncurses

### PR DESCRIPTION
**Pull request by IsabelParedes**
A dependency for R.

### CODE REVIEW

**Comment by DerThorsten** [comment]
@IsabelParedes there is some dedicated section on crosscompiling mentioning the `make_hash` function

https://github.com/gittup/ncurses/blob/gittup/INSTALL#L1710

**Comment by IsabelParedes** [comment]
Thanks @DerThorsten ! I had missed this. Following the INSTALL and config instructions, I set `BUILD_CC` to `gcc` to compile `make_hash` and `make_keys`. It seems that that worked. Now I just need to fix the install.

**Comment by IsabelParedes** [comment]
These are all JS files:

 - bin/clear
 - bin/infocmp
 - bin/ncurses6-config
 - bin/reset
 - bin/tabs
 - bin/tput
 - bin/tset

Not sure if the file extension will be an issue. Leaving a comment in case it comes up later.

**Comment by DerThorsten** [comment]
> These are all JS files:
> 
> * bin/clear
> * bin/infocmp
> * bin/ncurses6-config
> * bin/reset
> * bin/tabs
> * bin/tput
> * bin/tset
> 
> Not sure if the file extension will be an issue. Leaving a comment in case it comes up later.

I prefer to either have the **bin** files removed or we test them. 
Because often they do not work as often the *.wasm file is not installed.
You could try to add a test in the test section where you try to run the binaries with node

**Comment by IsabelParedes** [comment]
Hi @DerThorsten, I added the *.wasm files to bin/ and I added a test with nodejs for one of the binaries. This seems to work ok. Should I add more tests?

**Comment by DerThorsten** [comment]
> Hi @DerThorsten, I added the *.wasm files to bin/ and I added a test with nodejs for one of the binaries. This seems to work ok. Should I add more tests?

lets just merge it

**Pull request merged**
