### PR TITLE
Add missing widgetsnbextension to list of packages

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by DerThorsten** [comment]
@martinRenou if you now make some arbitrary changes inside the recipe folder, it should trigger that the ci rebuilds that pkg

**Comment by DerThorsten** [comment]
@martinRenou I thing this is a me error...I'll have a look

**Comment by DerThorsten** [comment]
a wait...its just a missing `ipykernel`

**Comment by martinRenou** [comment]
Removing the notebook dependency for now... Let's track this in this issue https://github.com/emscripten-forge/recipes/issues/63 for now?

**Comment by DerThorsten** [comment]
you need a section like here:
https://github.com/emscripten-forge/recipes/blob/0eba8b0f7d53569cf50b56d0bb8c107e773c2595/recipes/regex/recipe.yaml#L35
and a test_*.py in the recipes root

**Comment by martinRenou** [comment]
I don't understand the failure?

```
/home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/test_tmp/conda_test_runner.sh: /home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python: /home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/_build_env/venv/build/bin/python3: bad interpreter: No such file or directory
/home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/test_tmp/conda_test_runner.sh: /home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python: /home/runner/micromamba/envs/ci-env/conda-bld/widgetsnbextension_1652434452768/_build_env/venv/build/bin/python3: bad interpreter: No such file or directory
```

**Comment by DerThorsten** [comment]
@martinRenou just remove the test section from your recipe and add a new test section as for the other recipes (for example this one https://github.com/emscripten-forge/recipes/blob/main/recipes/regex/recipe.yaml#L35-#L38)

**Comment by martinRenou** [comment]
I don't understand why the test is still trying to pull notebook?

Anyway I guess we don't have a choice for now and need to make an ipykernel package if we want to use ipywidgets. Because ipywidgets [needs it anyway](https://github.com/conda-forge/ipywidgets-feedstock/blob/main/recipe/meta.yaml#L24). I've been wanting to cut this ipykernel dependency for some time now, as it's been annoying for xeus-python and pyolite too.

In order to cut this ipykernel dependency in ipywidgets we need to resolve this https://github.com/jupyter-xeus/xeus-python/issues/342.

**Comment by martinRenou** [comment]
One other temporary solution could be to add an ipywidgets recipe here that does not require ipykernel

**Comment by martinRenou** [comment]
Thanks for fixing it!

**Pull request merged**
