### PR TITLE
Add freetype

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
I think I'm not too far from having it right. 

I was thinking we could make proper recipes using the "ports" feature from embuilder. Pausing this work for now though.

**Comment by DerThorsten** [comment]
emscripten-ports seems like its not supported that much anymore  https://github.com/emscripten-ports 
all of them are "Public archive"

**Comment by DerThorsten** [comment]
so probably its better to use use https://github.com/freetype/freetype directly

**Comment by martinRenou** [comment]
Ports live in the emscripten repositories now probably? https://github.com/emscripten-core/emscripten/blob/main/tools/ports/freetype.py

It does look maintained (most commits were from 3 months ago under the ports directory)

**Comment by DerThorsten** [comment]
ok, then its fine with me

**Pull request closed without merging**
