### PR TITLE
update emscripten package

### PR DESCRIPTION
**Pull request by wolfv**
This also makes it easier to add new releases as we re-use the PKG_VERSION.

Will need to check what's wrong in boa -- run exports is not properly working. If we get it to work, we have a nice mutex package.

### CODE REVIEW

**Comment by DerThorsten** [comment]
looks good to me

**Comment by wolfv** [comment]
let me try to have a look and fix boa's run exports handling first :)

**Comment by DerThorsten** [comment]
I merged boa's main into the boa branch we are using. 
What else do we need to land this?

**Comment by wolfv** [comment]
We need to decide on a rebuild I guess, that's all

**Comment by wolfv** [comment]
@DerThorsten we should also try to align with pyodide on the python library triplet thing. Would it be enough to change `wasm32-unknown-emscripten` in all places in sysconfigdata?

**Pull request closed without merging**
