### PR TITLE
Add Clarabel

### PR DESCRIPTION
**Pull request by KGB99**
Currently without tests integrated.
`pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/clarabel`
returns a maturin failure where it says no python interpreter was found:
```
Running command Preparing metadata (pyproject.toml)
 │ │   📦 Including license file "/Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718116264/work/LICENSE.md"
 │ │   🍹 Building a mixed python/rust project
 │ │   🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
 │ │   💥 maturin failed
 │ │     Caused by: $PREFIX/bin/python is not a valid python interpreter
 │ │     Caused by: Failed to get information from the python interpreter at $PREFIX/bin/python
 │ │     Caused by: platform.system() in python, unknown, and the rust target, Target { os: Macos, arch: X86_64, env: Unknown, triple: "x86_64-apple-darwin", cross_compiling: false, rustc_version: Version
 │ │ Meta { semver: Version { major: 1, minor: 77, patch: 2 }, commit_hash: Some("25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04"), commit_date: Some("2024-04-09"), build_date: None, channel: Stable, host: "x86
 │ │ _64-apple-darwin", short_version_string: "rustc 1.77.2 (25ef9e3d8 2024-04-09)", llvm_version: Some(LlvmVersion { major: 17, minor: 0 }) }, user_specified: false }, don't match ಠ_ಠ
 │ │   Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-modern-metadata-q6r6o7fo', '--interpre
 │ │ ter', '$PREFIX/bin/python']' returned non-zero exit status 1.
```
When I then try to debug with conda_build.sh in the work directory it builds successfully by "not using a  specific python interpreter":
```
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
```

### CODE REVIEW

**Comment by KGB99** [comment]
```
 │ ╭─ Running build script
 │ │ Setting up cross-python
 │ │ + $BUILD_PREFIX/bin/python -m pip install . -vv
 │ │ Using pip 24.0 from $BUILD_PREFIX/venv/lib/python3.11/site-packages/pip (python 3.11)
 │ │ Non-user install because user site-packages disabled
 │ │ Ignoring indexes: https://pypi.org/simple
 │ │ Created temporary directory: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu
 │ │ Initialized build tracking at /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu
 │ │ Created build tracker: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu
 │ │ Entered build tracker: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu
 │ │ Created temporary directory: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-install-3a_susyw
 │ │ Created temporary directory: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-ephem-wheel-cache-uc4np15k
 │ │ Processing /Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work
 │ │   Added file:///Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work to build tracker '/private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu'
 │ │   Created temporary directory: /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-modern-metadata-zuf_1yjx
 │ │   Preparing metadata (pyproject.toml): started
 │ │   Running command Preparing metadata (pyproject.toml)
 │ │   📦 Including license file "/Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work/LICENSE.md"
 │ │   🍹 Building a mixed python/rust project
 │ │   🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
 │ │   💥 maturin failed
 │ │     Caused by: $PREFIX/bin/python is not a valid python interpreter
 │ │     Caused by: Failed to get information from the python interpreter at $PREFIX/bin/python
 │ │     Caused by: platform.system() in python, unknown, and the rust target, Target { os: Macos, arch: X86_64, env: Unknown, triple: "x86_64-apple-darwin", cross_compiling: false, rustc_version: Version
 │ │ Meta { semver: Version { major: 1, minor: 77, patch: 2 }, commit_hash: Some("25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04"), commit_date: Some("2024-04-09"), build_date: None, channel: Stable, host: "x86
 │ │ _64-apple-darwin", short_version_string: "rustc 1.77.2 (25ef9e3d8 2024-04-09)", llvm_version: Some(LlvmVersion { major: 17, minor: 0 }) }, user_specified: false }, don't match ಠ_ಠ
 │ │   Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-modern-metadata-zuf_1yjx', '--interpre
 │ │ ter', '$PREFIX/bin/python']' returned non-zero exit status 1.
 │ │   Checking for Rust toolchain....
 │ │   Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-modern-metadata-zuf_1yjx --interpreter $PREFIX/bin/python`
 │ │   error: subprocess-exited-with-error
 │ │   
 │ │   × Preparing metadata (pyproject.toml) did not run successfully.
 │ │   │ exit code: 1
 │ │   ╰─> See above for output.
 │ │   
 │ │   note: This error originates from a subprocess, and is likely not a problem with pip.
 │ │   full command: $PREFIX/bin/python $BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/mt/hfrbrgm93kb4
 │ │ 747gcgtc2l2c0000gn/T/tmpi8egkstu
 │ │   cwd: /Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work
 │ │   Preparing metadata (pyproject.toml): finished with status 'error'
 │ │ error: metadata-generation-failed
 │ │ × Encountered error while generating package metadata.
 │ │ ╰─> See above for output.
 │ │ note: This is an issue with the package mentioned above, not pip.
 │ │ hint: See above for details.
 │ │ Exception information:
 │ │ Traceback (most recent call last):
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
 │ │     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
 │ │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 766, in prepare_metadata_for_build_wheel
 │ │     return super().prepare_metadata_for_build_wheel(
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
 │ │     return self._call_hook('prepare_metadata_for_build_wheel', {
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
 │ │     self._subprocess_runner(
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
 │ │     call_subprocess(
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
 │ │     raise error
 │ │ pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1
 │ │ The above exception was the direct cause of the following exception:
 │ │ Traceback (most recent call last):
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
 │ │     status = run_func(*args)
 │ │              ^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
 │ │     return func(self, options, args)
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
 │ │     requirement_set = resolver.resolve(
 │ │                       ^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
 │ │     collected = self.factory.collect_root_requirements(root_reqs)
 │ │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
 │ │     reqs = list(
 │ │            ^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
 │ │     cand = self._make_base_candidate_from_link(
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
 │ │     self._link_candidate_cache[link] = LinkCandidate(
 │ │                                        ^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
 │ │     super().__init__(
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
 │ │     self.dist = self._prepare()
 │ │                 ^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
 │ │     dist = self._prepare_distribution()
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
 │ │     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
 │ │     return self._prepare_linked_requirement(req, parallel_builds)
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
 │ │     dist = _get_prepared_distribution(
 │ │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
 │ │     abstract_dist.prepare_distribution_metadata(
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
 │ │     self.req.prepare_metadata()
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 579, in prepare_metadata
 │ │     self.metadata_directory = generate_metadata(
 │ │                               ^^^^^^^^^^^^^^^^^^
 │ │   File "$BUILD_PREFIX/venv/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
 │ │     raise MetadataGenerationFailed(package_details=details) from error
 │ │ pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
 │ │ Removed file:///Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work from build tracker '/private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu'
 │ │ Removed build tracker: '/private/var/folders/mt/hfrbrgm93kb4747gcgtc2l2c0000gn/T/pip-build-tracker-0826h8zu'
 │ │
 │ ╰─────────────────── (took 15 seconds)
 │
 ╰─────────────────── (took 37 seconds)
 × error Error building package: Script failed with status Some(1).
 × error Work directory: "/Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work"
 × error To debug the build, run it manually in the work directory (execute the `./conda_build.sh` or `conda_build.bat` script)
Error:   × Script failed with status Some(1).
  │ Work directory: "/Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718115621/work"
  │ To debug the build, run it manually in the work directory (execute the `./conda_build.sh` or `conda_build.bat` script)
```

This is the error code generated when building with pixi

**Comment by KGB99** [comment]
The tests on the CI pass so I will try to integrate tests now.

**Comment by DerThorsten** [comment]
> Currently without tests integrated. `pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/clarabel` returns a maturin failure where it says no python interpreter was found:


so for [recipes with maturin](https://github.com/search?q=repo%3Aemscripten-forge%2Frecipes%20maturin&type=code) we do 
```
export MATURIN_PYTHON_SYSCONFIGDATA_DIR=${PREFIX}/etc/conda/_sysconfigdata__emscripten_wasm32-emscripten.py
${PYTHON} -m pip  install . -vvv
```
but it seems like it is not needed in this case anymore as this is building

**Comment by KGB99** [comment]
> > Currently without tests integrated. `pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/clarabel` returns a maturin failure where it says no python interpreter was found:
> 
> so for [recipes with maturin](https://github.com/search?q=repo%3Aemscripten-forge%2Frecipes%20maturin&type=code) we do
> 
> ```
> export MATURIN_PYTHON_SYSCONFIGDATA_DIR=${PREFIX}/etc/conda/_sysconfigdata__emscripten_wasm32-emscripten.py
> ${PYTHON} -m pip  install . -vvv
> ```
> 
> but it seems like it is not needed in this case anymore as this is building

I tried adding the exports line but it didnt build then, so ill keep it like this for now

**Review by IsabelParedes — APPROVED** [review]

**Pull request merged**
