### PR TITLE
Add eigen recipe

### PR DESCRIPTION
**Pull request by traversaro**
Package added following the docs in https://blog.jupyter.org/mamba-meets-jupyterlite-88ef49ac4dc8 .

### CODE REVIEW

**Comment by wolfv** [comment]
Hi @traversaro, awesome! Hopefully we can get this across the finish line on Monday or Tuesday, it shouldn't be too hard :)

**Comment by wolfv** [comment]
A tiny space after the `\ ` was breaking the recipe apparently! :)

**Comment by traversaro** [comment]
> A tiny space after the `\ ` was breaking the recipe apparently! :)

Agh, sorry for that. It is not the first time it happens to me.

**Comment by traversaro** [comment]
@wolfv the post-merge CI job failed: https://github.com/emscripten-forge/recipes/runs/7412543614 .

**Pull request merged**
