### PR TITLE
Package xarray

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by wolfv** [comment]
Hi @davidbrochart it's not necessary to package `noarch` packages seperately -- you can already use them (as long as we have all dependencies) from conda-forge!

**Comment by wolfv** [comment]
E.g. for jupyterlite:

```
pip install jupyterlite jupyterlite-xeus-python
jupyter lite build --XeusPythonEnv.packages=numpy,matplotlib,ipyleaflet,xarray
```

Shoudl set you up with xarray from conda-forge in the `xpython` kernel.

**Comment by davidbrochart** [comment]
Thanks @wolfv !

**Comment by davidbrochart** [comment]
> `jupyter lite build --XeusPythonEnv.packages=xarray`

I get this error:
```
error    libmamba File not valid: file size doesn't match expectation "/home/david/mambaforge/pkgs/xeus-python-0.14.2-py310h5820cd7_0.tar.bz2"
    Expected: 3318641
    Actual: 3266225
python                                              14.8MB @   3.4MB/s  4.3s
xeus-python                                          3.3MB @ 751.2kB/s  1.2s
xeus-python-0.14.2-py310h5820cd7_0.tar.bz2 tarball has incorrect size
pandas                                               9.8MB @   2.0MB/s  2.6s
```

**Comment by wolfv** [comment]
Hmm. Can you remove the file from your disk?

**Comment by davidbrochart** [comment]
It actually doesn't exist:
```bash
ls /home/david/mambaforge/pkgs/xeus-python-0.14.2-py310h5820cd7_0.tar.bz2
ls: cannot access '/home/david/mambaforge/pkgs/xeus-python-0.14.2-py310h5820cd7_0.tar.bz2': No such file or directory
```

**Comment by wolfv** [comment]
Then retrying might work already

**Comment by davidbrochart** [comment]
I tried several times, same result.

**Comment by wolfv** [comment]
hmm, indeed, it seems like a problem on our quetz instance 😢  let me check

**Comment by wolfv** [comment]
I just pushed a new build from xeus-python. Should be available in ~10 minutes.

**Comment by davidbrochart** [comment]
Thanks, that works now (after a `mamba clean -i`).

**Pull request closed without merging**
